### ISSUE TITLE
Switch to manifest-based events and use parameterized event messages

### ISSUE THREAD

**Issue by iadgovuser1** [nsacyber/PRUNE#1]
Switch to using a manifest for logging events and used parameterized event log messages so the PRUNE event logs are easier to parse in SIEMs. ecmangen.exe is no longer include in the Windows SDK so here are some links to help with creating a manifest:
* https://blogs.windows.com/buildingapps/2017/07/12/windows-10-sdk-preview-build-16232-released/
* https://docs.microsoft.com/en-us/windows/desktop/wes/writing-an-instrumentation-manifest
* https://docs.microsoft.com/en-us/windows/desktop/wes/eventmanifestschema-schema
* https://docs.microsoft.com/en-us/windows/desktop/wes/eventschema-schema
* https://docs.microsoft.com/en-us/windows/desktop/wes/message-compiler--mc-exe-

**Comment by iadgovuser42** [comment]
Manifest based events have been implemented. There is a little cleanup work remaining, but I've merged the feature in.
