### ISSUE TITLE
Sync version numbering

### ISSUE THREAD

**Issue by iadgovuser1** [nsacyber/PRUNE#10]
The following files:
* /Prune/Properties/AssemblyInfo.cs
* /PruneLibrary/Properties/AssemblyInfo.cs
* /PruneService/Properties/AssemblyInfo.cs

contain:

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

The following files:
* /PruneInstaller_x86/Product.wxs
* /PruneInstaller_x64/Product.wxs

contain:

Version="1.0.0"

Need to pick a versioning scheme and ensure all these references get updated. Probably should follow Semantic Versioning: https://semver.org/

Some references for Wix:
* https://stackoverflow.com/questions/626033/how-can-i-set-the-wix-installer-version-to-the-current-build-version
* https://stackoverflow.com/questions/46835233/configure-wix-to-automatically-set-product-version-attribute
* https://stackoverflow.com/questions/43231283/wix-dont-show-build-number-from-productversion
* https://www.firegiant.com/wix/tutorial/upgrades-and-modularization/

**Comment by iadgovuser49** [comment]
Fixed Version Numbering in https://github.com/nsacyber/PRUNE/commit/90505b8f3e3ae72fb31177f9a8cb6d58868762dc.
