### ISSUE TITLE
Update manufacturer

### ISSUE THREAD

**Issue by iadgovuser1** [nsacyber/PRUNE#11]
The following files:
* /PruneInstaller_x86/Product.wxs
* /PruneInstaller_x64/Product.wxs

contain:

Manufacturer="Y11121"

This value need to be updated C151 or the division title.

**Comment by iadgovuser49** [comment]
Updated manufacturer to C151 in https://github.com/nsacyber/PRUNE/commit/90505b8f3e3ae72fb31177f9a8cb6d58868762dc.
