### ISSUE TITLE
Consider adding hardware information related to performance measurements

### ISSUE THREAD

**Issue by iadgovuser1** [nsacyber/PRUNE#2]
Performance is relative to the hardware. Probably useful to also log a few pieces of hardware information so then we can bin performance by like systems, if necessary.

Processor info (Win32_Processor fields):
* Description: Get-WmiObject -Class Win32_Processor | Select-Object -Property Description -ExpandProperty Description
* Name: Get-WmiObject -Class Win32_Processor | Select-Object -Property Name -ExpandProperty Name
* NumberOfCores (Physical cores): Get-WmiObject -Class Win32_Processor | Select-Object -Property NumberOfCores -ExpandProperty NumberOfCores
* NumberOfLogicalProcessors (Logical processors): Get-WmiObject -Class Win32_Processor | Select-Object -Property NumberOfLogicalProcessors -ExpandProperty NumberOfLogicalProcessors

Computer info (Win32_ComputerSystem fields):
* Manufacturer: 
* Model: 
* NumberOfProcessors (Physical processors): Get-WmiObject -Class Win32_ComputerSystem | Select-Object -Property NumberOfProcessors -ExpandProperty NumberOfProcessors

Physical drive info (Win32_DiskDrive fields): - get system drive, then get the volume and match that to the correct physical drive
* Manufacturer
* Model

Total physically installed RAM:
* https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getphysicallyinstalledsystemmemory

Make sure all strings are trimmed before they are used in event log messages.

Info should probably go in the summary event log event.

**Comment by iadgovuser1** [comment]
Looks like ce0186c and 669ce0f might address this.

**Comment by iadgovuser42** [comment]
This has been done, however it could be improved still. Hardware information is all just single strings. Support could be added so that, for example, multiple disks on the system are represented in an array of information rather than one string that represents all disks.

This would need variable-length arrays to be added to the manifests and data passed in correctly.

**Comment by iadgovuser49** [comment]
Updated manifest to use variable-length arrays for hardware information. See https://github.com/nsacyber/PRUNE/commit/ad404e2bda937912f12b7179fa43afa3adc8fe66 and  https://github.com/nsacyber/PRUNE/commit/be333a1a4748363d9f232794196c1734bc8eb5e0
