### ISSUE TITLE
Add support for Group Policy based configuration

### ISSUE THREAD

**Issue by iadgovuser1** [nsacyber/PRUNE#7]
Add Group Policy support so we don't have to rely on pushing out files to make configuration changes. Add support for:

* config.json
    * calculateStatisticsInterval 
    * writeCacheToFileInterval
    * dataRecordingInterval 
    * whitelistCheckInterval 
    * configCheckInterval 
* whitelist.txt
    * process syntax
    * module syntax
    * process and module syntax

Probably need 6 policies: 5 policies for config.json and 1 policy for whitelist support.

Group Policy configuration should take precedence over local configuration files so when a specific GP value is configured for a specific setting, then the specific local configuration file setting should be ignored.

Will need to create an admx and adml file to contain the settings. The installer will need to place these files in C:\Windows\PolicyDefinitions\ (admx in root and adml in en-us subfolder). Example from a previous project: https://github.com/nsacyber/Driver-Collider/tree/master/collision Also see the GP schema reference at https://msdn.microsoft.com/en-us/windows/desktop/aa373476 but the easiest way to get started is by looking at examples from C:\Windows\PolicyDefinitions\  and C:\Windows\PolicyDefinitions\en-us\

Might need to genericize the configuration parts of the code to use an interface and then have one class the implements reading the file-based config, one class that implements reading the GP-based config. Something like a ConfigurationManagement class might be needed to enforce the "GP setting overrides local config file setting" concept that spits out the effective, final configuration. There should be enough flexibility using this type of implementation so 1 setting could come from Group Policy (if configured) while the rest of the settings could come from the files (in the cases where GP isn't configured for the setting).

**Comment by iadgovuser49** [comment]
Added support for Group Policy based configuration in https://github.com/nsacyber/PRUNE/commit/f0bf63d332ba2e9558f9c29cfcd0a1a43a8c85e5 and https://github.com/nsacyber/PRUNE/commit/b61482d265f76dc84f1a457f0ee32347e1933f06.
